### ISSUE TITLE
Glassfish v4.1.1 & MediaTypes.APPLICATION_JSON

### ISSUE THREAD

**Issue by stefanmichalk** [tinabrunner/FreezerManagement#15]
### Betrifft

-  Glassfish v4.1.1 
- in Verbindung mit allen Rückgaben der (REST)Controller != `String` (`Boolean`, `List`, etc.)

### Fehler
 ```java
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.persistence.jaxb.BeanValidationHelper
```

### Auswirkung(en)

Alle (REST)Anfragen seitens der Website werden intern mit HTTP/500 (Internal Server Error) quittiert. Eine Weiterverarbeitung ist nicht möglich.

## Lösungsvorschlag

Alle Rückgaben der Controller auf `String` anpassen und mit `Gson()` konvertieren

### Auswirkung(en)

Keine, da die Controller laut Quelltext nur nach außen kommunizieren und gültige Responses liefern kann die Weiterverarbeitung seitens Website stattfinden.

#### Fehlerhaftes Beispiel in _ShoppingListController.java_
```java
// ----|   FEHLERSTELLE     |------
public List<ShoppingListItem> getAllProductsFromShoppingList() throws ParseException {
		List<ShoppingListItem> shoppingListProducts = db_shoppingList.getAllProductsFromShoppingList();
		return shoppingListProducts;
	}
```

#### Vorgeschlagene Korrektur

```java
public String getAllProductsFromShoppingList() throws ParseException {
		List<ShoppingListItem> shoppingListProducts = db_shoppingList.getAllProductsFromShoppingList();
		return new Gson().toJson(shoppingListProducts);
	}
```

**Comment by phil294** [comment]
Fehler ist 4.1.1-spezifisch. Alternative & momentane Lösung des Problems ist Downgrade auf 4.0

**Comment by stefanmichalk** [comment]
Ich weiß :) geht nur darum, falls einer 4.1.1 haben sollte. 
Leider ist der Fehler im Nightly Build in Glassfish 4.1.1 noch nicht gefixt.

4.0.0 ohne Probleme.

**Comment by stefanmichalk** [comment]
Der Bezug auf die Version ist oben auch explizit angemerkt :)

Der Fix wäre ein Workaround für alle Versionen. 
That's all.
